project:
  type: website
  output-dir: docs

website:
  title: "Econ8502"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: Assignments
        menu:
          - assignments/Assignment-1.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



