---
title: "Assignment 3"
---

# Estimating a Dynamic Discrete Choice Model

## The Model

Consider the following infinite horizon, dynamic labor supply problem.

- There are two choices in the model, work ($j=0$), or don't work ($j=0$)
- The wage $w$ is a state variable with two values, $w_{L}<w_{H}$.
- The evolution of the wage depends on the current wage and work behavior as follows:
    - $P(w_{t+1}=w_{H}|w_{t}=w_{H},j=1) = 1$
    - $P(w_{t+1}=w_{L}|w_{t}=w_{H},j=0) = \pi$
    - $P(w_{t+1}=w_{L}|w_{t}=w_{L},j=0) = 1$
    - $P(w_{t+1}=w_{H}|w_{t}=w_{L},j=1) = \pi$
- Thus, human capital appreciates and depreciates with symmetric probabilities given by $\pi$ when working / not working.
- Per-period payoffs are given by:
$$ U_{n,t,j}(w) = j \times \left[w - \kappa (1-j_{t-1})\right] + \epsilon_{ntj} $$
where $\epsilon_{ntj}$ is an iid type 1 extreme value shock with location parameter 0 and scale parameter $\sigma$, and $j_{t-1}$ indicates whether person $n$ worked in the previous period. You can interpret $\kappa$ therefore as a cost of joining the labor force.
- Agents discount future payoffs at an exponential rate, $\beta$.

## Part 1

Write code to solve this model and calculate the conditional probability of working given human capital ($w$) and lagged work behavior $j_{-1}$.

## Part 2

Write code to simulate a panel dataset of choices ($j$) and wages ($w$) from the model consisting of $N$ individuals and $T$ time periods per individual. You can make whatever assumption you like regarding initial conditions. You can set default parameters to whatever you like.

## Part 3

The complete set of model parameters is:

$$ \theta = (\pi,\kappa,\beta,\sigma).$$

Has this model specification already imposed a location normalization on utilities? What about a scale normalization? If not, state the normalization you are going to make. **Note**: wages and hence $w_{L}$ and $w_{H}$ should be treated as if they are data (i.e. known), not parameters.

## Part 4

Assume you know the values of $\beta$ and $\pi$. Write code to estimate -- by maximizing the log-likelihood of observed choices -- the remaining model parameters and write a monte-carlo simulation to document the performance of your estimator.

## Part 5

Now try estimating $\beta$ in addition to the parameters from Part 4. Does $\beta$ appear to be identified? Do you have some intuition for why / why not?