---
title: "Assignment 1"
---

## Setup: Loading the Data

Here is code to load the dataset and do a little cleaning / filtering.

The sample is all mothers in the PSID who are unmarried at the time of their first childbirth.

```{julia}
using CSV, DataFrames, DataFramesMeta

data = @chain begin
    CSV.read("../children-cash-transfers/data/MainPanelFile.csv",DataFrame,missingstring = "NA")
    @select :MID :year :wage :hrs :earn :SOI :CPIU :WelfH :FSInd
    @subset :year.>=1985 :year.<=2010
    @transform :AFDC = :WelfH.>0
    @rename :FS = :FSInd
    end
```

You may be unfamiliar with some of these commands, which make use of `DataFrames` and `DataFramesMeta`. In particular, think of the `@chain` macro as a way to compose functions. So for example:

```{julia}
#| eval: false
d1 = @chain d2 begin
    func1(x)
    func2(y)
    func3(z)
end
```

is equivalent to calling:

```{julia}
#| eval: false
d1 = func3(func2(func1(d2,x),y),z)
```

If you want to understand better, google is your friend!

## Question 1

Calculate average welfare participation (`AFDC`) by year and plot it. What do you think happened with welfare participation in 1996 and after? If you don't know the historical context, a quick search online or a read of [this](/papers/DesigningCashTransfers_Children_Draft.pdf) paper should help you out.


If you are new to `julia`, here is average hours calculated and plotted to get you started.

```{julia}
using StatsPlots, Statistics

d = @chain data begin
    groupby(:year)
    @combine :Hours = mean(skipmissing(:hrs))
    @subset .!isnan.(:Hours)
end

@df d plot(:year,:Hours, legend = :none, linewidth = 2)
xlabel!("Year")
ylabel!("Average Welfare Participation")

```

## Question 2

Now write code to 

(0) Deflate earnings by CPI (`CPIU`).
(1) Calculate annual average earnings for each individual (identified by `MID`).
(3) Drop individuals with fewer than 10 years of data.
(4) Categorize individuals by whether their average earnings is below or above the median across individuals.
(5) Plot average participation in each year for individuals in each of these two categories.

Do you think this pattern is likely to be generated by a model without persistent unobserved heterogeneity? No strictly correct answer here, just curious to read what you think.

In case it helps, here is code for the first three steps. You could edit this to add additional operations to the chain or work with `d` directly.

```{julia}
d = @chain data begin
    @transform :earn = :earn ./ :CPIU
    groupby(:MID)
    @combine :T = sum(.!ismissing.(:earn)) :earn = mean(skipmissing(:earn)) 
    @subset :T .>= 10
end

```

## Question 3

This question is to familiarize you with the module `Tranfers.jl` which will enable you to calculate post-tax and transfer income for individuals given their earnings, non-labor income, state, year, and family size. The function `budget` in this module takes the arguments:

- `E`: monthly earnings (either real or nominal)
- `N`: monthly non-labor income (real or nominal)
- `SOI`: the [SOI code](https://taxsim.nber.org/statesoi.html) for state of residence
- `year`: calendar year
- `num_kids`: the number of children
- `cpi`: set to 1. if `E` and `N` are nominal
- `p`: equal to 0 if no programs, 1 if food stamps, 2 if food stamps + welfare.

For example the function call:

```{julia}
#| eval: false
Transfers.budget(500.,0.,23,2000,2,1.,2)
```

calculates net income for a mother in Michigan (SOI code 23) with 2 kids, nominal labor income of $500 a month in the year 2000, and no non-labor income.

```{julia}
include("../children-cash-transfers/src/Transfers.jl")

Transfers.budget(500.,0.,23,2000,2,1.,2)

```

Create a graph that represents total net **transfers** for a single mother with two kids in the years 1990 and 2000 and in the states of Mississippi and New York. Depict these transfers as a function of earnings between the values of 0 and \$1,000 a month (nominal). You can assume that all households are receiving both food stamps and welfare.

What do you make of the differences in these transfers across states and over time?
